language: scala
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.12 # Use for compatible due to https://github.com/scoverage/sbt-scoverage/issues/319
  - 2.13.1
install:
  - pip install --user codecov
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport scalastyle;
  - codecov
